<?php
/**
 * Vendor file server.
 * Sirve bundles pre-generados por build.sh desde app/cach/.
 * En modo debug, concatena archivos al vuelo (sin cache).
 *
 * Uso: npm run build  (genera los bundles minificados)
 */

$vendor = $_GET['vendor'] ?? '';

// Map vendor type → file extension
$typeMap = [
	'css'    => 'css',
	'js'     => 'js',
	'debug'  => 'debug',
	'mobile' => 'mobile',
	'test'   => 'test',
];

if (!isset($typeMap[$vendor])) {
	http_response_code(404);
	die();
}

$contentType = ($vendor === 'css') ? 'text/css' : 'application/javascript';
$cachedir    = __DIR__ . '/cach/';

// debug and mobile use their own cache names
$cacheNames = [
	'css'    => '1',
	'js'     => '1',
	'debug'  => 'debug',
	'mobile' => 'mobile',
	'test'   => '1',
];

$ext       = ($vendor === 'css') ? 'css' : $typeMap[$vendor];
$cachefile = $cachedir . sha1($cacheNames[$vendor]) . '.' . $ext;

// Serve cached bundle if it exists (generated by build.sh)
if (file_exists($cachefile)) {
	header("Content-Type: $contentType");
	readfile($cachefile);
	die();
}

// ─── Fallback: concatenate on-the-fly (dev only) ────────────────────────
// This runs when build.sh hasn't been executed yet.
// It reads local files and concatenates them without minification.

$rootDir = dirname(__DIR__); // project root

function readLocalFile($path) {
	global $rootDir;

	// Absolute path from web root (e.g. /assets/vendor/js/...)
	if (strpos($path, '/') === 0) {
		$full = $rootDir . $path;
		// Strip query string for file reads
		$full = preg_replace('/\?.*$/', '', $full);
		if (file_exists($full)) {
			return file_get_contents($full);
		}
		return "/* MISSING: $path */\n";
	}

	// Relative path (e.g. cach/..., scripts/...)
	$clean = preg_replace('/\?.*$/', '', $path);
	if (file_exists($clean)) {
		return file_get_contents($clean);
	}

	// External URL
	if (filter_var($path, FILTER_VALIDATE_URL)) {
		$ctx = stream_context_create([
			'ssl'  => ['verify_peer' => false, 'verify_peer_name' => false],
			'http' => ['timeout' => 10],
		]);
		$content = @file_get_contents($path, false, $ctx);
		return $content !== false ? $content : "/* FETCH FAILED: $path */\n";
	}

	// Inline code (e.g. widget bridge)
	return $path;
}

// ─── File lists (same as build.sh) ──────────────────────────────────────
$_v = '/assets/vendor';

$files_css = [
	'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;900&display=swap',
	'https://fonts.googleapis.com/icon?family=Material+Icons',
	'https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap',
	'/app/css/fonts.css',
	"$_v/css/bootstrap-3.4.1.min.css",
	'/app/css/app.css',
	"$_v/css/animate-4.0.0.compat.min.css",
	"$_v/css/bootstrap-datetimepicker-4.17.47.min.css",
	"$_v/css/jquery.toast-1.3.2.min.css",
	'/panel/css/color-selector-2.css',
	"$_v/css/sweetalert2-7.33.1.min.css",
	'/assets/css/iguider.css',
	'/assets/css/iguider.theme-material.css',
	'/app/css/ncmCalendars.css',
	'/app/css/chosen.css',
	'/app/css/custom.css',
];

$files_js = [
	"$_v/js/jquery-3.6.3.min.js",
	"$_v/js/bootstrap-3.4.1.min.js",
	"$_v/js/moment-2.24.0-with-locales.min.js",
	"$_v/js/moment-locale-es.js",
	"$_v/js/jquery.dataTables-1.10.22.min.js",
	"$_v/js/isMobile-0.4.1.min.js",
	"$_v/js/offline-0.7.19.min.js",
	"$_v/js/chosen-1.8.7.min.js",
	"$_v/js/jquery.number-2.1.6.min.js",
	"$_v/js/mousetrap-1.6.3.min.js",
	"$_v/js/jquery.actual-1.0.19.min.js",
	"$_v/js/simpleStorage-0.2.1.min.js",
	"$_v/js/pouchdb-7.2.1.min.js",
	"$_v/js/lz-string-1.4.4.min.js",
	'/panel/scripts/written-number.min.js',
	"$_v/js/rsvp-4.8.5.min.js",
	'/app/scripts/sha256.js',
	"$_v/js/jsrsasign-all-min.js",
	"$_v/js/qz-tray-2.2.1.min.js",
	'/app/scripts/sign-message.js',
	"$_v/js/bootstrap-datetimepicker-4.17.47.min.js",
	'/panel/scripts/color-selector-2.js',
	"$_v/js/libphonenumber-1.6.8.min.js",
	"$_v/js/Chart-2.9.4.min.js",
	"$_v/js/sweetalert2-7.33.1.min.js",
	"$_v/js/push-1.0.8.min.js",
	"$_v/js/mustache-4.0.1.min.js",
	'/app/scripts/iguider.stub.js',
	"$_v/js/jquery.fullscreen-1.1.5.min.js",
	'/assets/panel/js/fileReader.min.js',
	'/assets/scripts/ncmDropbox.min.js',
	"$_v/js/leaflet-1.7.1.js",
	"$_v/js/leaflet-routing-machine-3.2.12.js",
	'/assets/scripts/hereRouting.min.js',
	"$_v/js/fingerprintjs-3.min.js",
	"$_v/js/jquery.geolocation-1.0.50.min.js",
	"$_v/js/jquery.toast-1.3.2.min.js",
	'/app/scripts/ncm-ws.js',
	'/panel/scripts/rb.min.js',
	'/panel/scripts/num2word.js',
	'/panel/scripts/documentPrintBuilder.source.js',
	'/app/scripts/globalv2.js',
];

$files_debug = array_merge(
	["$_v/js/jquery-3.6.3.min.js", "$_v/js/fastclick-1.0.6.min.js"],
	array_slice($files_js, 1, -1), // skip jquery (already added) and globalv2
	["$_v/js/qrious.min.js", '/app/scripts/ncm-ws.js', '/app/scripts/debug.js']
);

$files_mobile = $files_debug; // same set

$fileLists = [
	'css'    => $files_css,
	'js'     => $files_js,
	'debug'  => $files_debug,
	'mobile' => $files_mobile,
	'test'   => [
		'/assets/panel/js/fileReader.min.js',
		'/assets/scripts/ncmDropbox.min.js',
		'/assets/scripts/hereRouting.min.js',
		'/assets/scripts/dpb.min.js',
	],
];

$files  = $fileLists[$vendor] ?? [];
$isDebug = ($vendor === 'debug');

// Concatenate
$contents = [];
foreach ($files as $file) {
	$contents[] = readLocalFile($file);
}
$buffer = implode("\n;\n", $contents);

// Cache unless debug mode
if (!$isDebug) {
	@mkdir($cachedir, 0755, true);
	file_put_contents($cachefile, $buffer);
}

header("Content-Type: $contentType");
echo $buffer;
